"""เพิ่มคอลัมน์ page ใน Comment

Revision ID: cdb84f9b5fe1
Revises: 
Create Date: 2025-02-22 16:58:14.779343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdb84f9b5fe1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page', sa.String(length=50), nullable=False, server_default="default"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('page')

    # ### end Alembic commands ###
